_extends: .github
repository:
  name: settings-test
  description: a repo for testing functionality of probot/settings
  homepage: 'https://github.com/travi-test/settings-test#readme'
  private: false
