_extends: .github
repository:
  name: settings-test
  description: a repo for testing functionality of probot/settings
  homepage: 'https://github.com/travi-test/settings-test#readme'
  private: false
  delete_branch_on_merge: false

teams:
  - name: triage
    permission: triage

milestones:
  - title: test-milestone
    description: this is a test
    state: open

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
      required_linear_history: false

  - name: alpha
    protection:
      enforce_admins: true
